version: '3.8'

services:
  dks_bot_test:
    build: .
    container_name: dks_bot_test_app
    restart: always
    env_file:
      - test.env
    volumes:
      - ./data_test:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"